### ISSUE TITLE
Add functionality to convert a textual representation of a field to a minefield model.

### ISSUE THREAD

**Issue by ilkutkutlar** [ilkutkutlar/minesweeper_model#1]

**Comment by 27Anurag** [comment]
Hello, I'm interested in adding this functionality, but this is my first opensource contribution. Could you please describe what kind of a textual representation are you expecting?
Regards.

**Comment by ilkutkutlar** [comment]
Hello,

Thank you for your interest in the project! No problem, I probably should have explained it a bit more. Currently, you'll see that when creating a `Field` class, the user enters the field dimensions and passes a list of two-tuples (x, y) representing the mine coordinates. I find this a bit inconvenient, so I was thinking it could be easier to have a method that takes a string like this:

```
x.....
...x..
.x....
```

and detect from the string that it has dimensions 6x3 and that the field has mines in the coordinates where there are `x` characters (e.g. here (0, 0), (3, 1), (1, 2)) and no mines where there are '.' characters. Then the method can use this information to create a `Field` object. So the textual representation is the same as the one output by the `render` method of the `Field` class.

If you are interested in developing this feature, I'd be very happy. If that's the case, please assign yourself to the issue and make a pull request when you are done writing the code and the relevant tests. It's not urgent, so please take your time and don't hesitate to ask more questions if you need to. Thank you again!

Regards

**Comment by 27Anurag** [comment]
Thanks for the detailed explanation! I would like to try making this feature, how do I assign myself for this? I know how to use GitHub but working with issue is new for me. 

Regards.

**Comment by ilkutkutlar** [comment]
There is an 'Assignees' section in this issue's page where you can click to assign yourself, it's on the right if you are on destop

**Comment by 27Anurag** [comment]
I've written the code for it and it is able to do the above-mentioned tasks, I've forked the repo and added a new python file to the repo, could you please help with how do commit that change from that forked repo to this repo? 
regards.

**Comment by ilkutkutlar** [comment]
Hello again, I've seen the repo you've forked and created a pull request for you, that you can see in the "Pull Requests" tab of this repo. The next step is to review the changes you've made, make changes if necessary, then merge the changes into the repository.

Regards

**Comment by ilkutkutlar** [comment]
Hello, further to my previous comment, I've reviewed your changes. Thank you very much for the effort you have put it. I've made some comments with suggestions for changes in your code to make it better aligned with the overall structure of the project. You can see them in the "Pull Requests" tab on this repository. Can I please ask that you read and apply them before I can merge your changes?
